### PR TITLE
add xtypeof() wrapper to allow running on gawk 4.1 and earlier

### PR DESCRIPTION
**Pull request by tyingq**
This adds a wrapper around typeof(), which didn't exist until gawk 4.2, so that it works on versions of gawk prior to that.

### CODE REVIEW

**Comment by rethab** [comment]
Thanks @tyingq would you mind removing the generated `.class` file? Even better, would you mind adding an entry to `.gitignore`? Thanks a lot!

**Comment by rethab** [comment]
Hi @tyingq would you mind creating a separate PR for the second commit about removing hexdump? The reason is that the first commit is a nobrainer, but I'm not sure if I want to merge the second, because I eventually want to be able to read multiple class files and I'm not sure how that would work with using `gawk` directly. With hexdump, however, I could do it line-by-line.

**Comment by tyingq** [comment]
Yes, sorry.   Hadn't done pull requests through github before.

**Comment by rethab** [comment]
Absolutely no problem :) Let me know if you are unsure how to go about it

**Comment by tyingq** [comment]
I think I have it in the right state now.

**Comment by rethab** [comment]
Thanks @tyingq this is great! :tada:

**Pull request merged**
